### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by rediffusion** [zanza00/random-theme-switcher#19]
I have the «VS Code» _latest version_.
Every time I open the «VS Code» this menu pop-up:

![image](https://user-images.githubusercontent.com/30071027/71760399-24935f00-2ece-11ea-86f5-7d1564c88c37.png)

 If I want to change some theme I need to open `User-Settings` _.json_ file then in this line insert theme name:
> "workbench.colorTheme": "One Dark Pro"

I've tried to put this in `package.json` file with no luck:

`"randomThemeSwitcher.themeList": [
        "Andromeda Italic",
        "Cobalt2",
        "Dracula",
        "Tomorrow Night Blue",
        "Ayu Dark",
        "One Monokai",
        "Night Owl"
]`

How could I change the theme with your super plugin!? With regards! ✌️

**Comment by Denis-net** [comment]
Hey @rediffusion ! 😄👋🏼

At the first launch it will ask you what kind of themes you would like to preload: both, ligth or dark.
(I contributed to that distinction, because i like the dark ones and in previous version it would load all of them).
You're actually right: at first glance it's not very clear... (we'll fix it 👍🏼)

This popup will only appear the first time (if you need it a later time, you can call `Random Theme: Copy All Installed Theme in settings`.

Not sure it's a typo or not, but the rigth file is : `settings.json` and you can reach it from the settings page:
![immagine](https://user-images.githubusercontent.com/45769702/71820678-24db5800-3090-11ea-8c6a-5db8a56289aa.png)

There you can specify the themeList:
![immagine](https://user-images.githubusercontent.com/45769702/71820541-aed6f100-308f-11ea-87d1-89b18dd65520.png)

You can also set a workspace themeList creating/writing inside ".vscode/settings.json" a themeList.

Don't forget to look at the `Switch Mode` option.😉

Have you found a bug ?

p.s. the popup will only appear if at startup it detects that the themeList is empty.
Can you read any suspicious warns/errors in the DevTools ?

**Comment by rediffusion** [comment]
@Denis-net 
 Hello mate 👏

 Anyway, it's not working! Here are my entries in _Settings.json_ file:
```
    "randomThemeSwitcher.themeList": ["Noctis Minimus", "Ayu One", "Dracula Soft", "eppz!"],
    "randomThemeSwitcher.switchMode": "startup",
```

Should I use such entries?
"workbench.colorTheme": "Noctis Minimus",
...with it or without entries, "Theme Random Swither" isn't working when I `close` the IDE and `reopen` it!

 Regards!

**Comment by Denis-net** [comment]
hmmm, very strange.
![immagine](https://user-images.githubusercontent.com/45769702/71877223-f067aa80-3128-11ea-977b-cff8bb8f19e0.png)
(I only found "Ayu One Dark" but even with "Ayu One" the others still work)
Try to set ".vscode/settings.json" inside a workspace (open a folder with vscode and add your keys there), then try to reopen and see if something has changed.
Even with that the app still popup you the first picker ?
What happens when you select an entry in the picker ?

It looks like a problem with the app accessing the configuration.
Nothing in the devtools ?
Have you tried to remove all the keys, set a theme and then select in the command palette: "Add current theme to settings" ?

**Comment by rediffusion** [comment]
@Denis-net 

 At starting the IDE I use `vs-dark` then press ESC.
In this folder, I have the same entries, I don't see any point in rewriting anything. 😕

> %APPDATA%\Code\User\settings.json

> Even with that the app still popup you the first picker?

 Not seen anymore any popup.

> What happens when you select an entry in the picker?

Nothing special just some field with prompt (if you... enter or ESC bla bla bla) --> [Screencast](https://www.screencast.com/t/ypanFfsPToHE).

> Nothing in the devtools?

Where is it?

> Have you tried to remove all the keys, set a theme and then select in the command palette: "Add current theme to settings" ?

Yes with no luck 😕

**Comment by Denis-net** [comment]
I didn't remember that there is that part too:
* With Esc you cancel the command, and this is the reason why nothing happens
* With Enter (without the regex, i.e. lefting the inputbox empty) it will compose for you the themeList,
* With Enter and a regex (say "Material") it will load all the themes of the previously chosen side exluding Material themes.

I see the encoding is UTF-8 so no problem with that.

> Where is it?

![immagine](https://user-images.githubusercontent.com/45769702/71882088-03cc4300-3134-11ea-9bb5-eae9b2d67017.png)
Here: VS Code is a Chrome in disguise (based on Chromium).😜

"workbench.colorTheme" is the standard VS Code key for changing the theme,
"randomThemeSwitcher.themeList" is the key which will be looked at startup from the extension and belongs only to the latter.

Try to press `Enter` to the question.

**Comment by Denis-net** [comment]
Ok, le's try another way:

Please, try to open a powershell terminal and run this code : 
```powershell
code --list-extensions | % { "code --install-extension $_" }
```
then send me back the result.

In this way i'll try to emulate your environment in a VM and see what's going wrong.
Maybe could be an extension called in some way that raise exceptions or something like that I still don't know.
The more information we got the faster a solution can be found.👍🏼

**Comment by rediffusion** [comment]
Deal, here you ho:

> code --install-extension trfr2h5mxe6eyejgts4uaakmutbhor5ric2zlvrh5yxuswlt326a.webassembly
> code --install-extension be5invis.vscode-custom-css
> code --install-extension blackmist.LinkCheckMD
> code --install-extension DavidAnson.vscode-markdownlint
> code --install-extension Denis-net.vscode-ahk-manager
> code --install-extension docsmsft.docs-article-templates
> code --install-extension docsmsft.docs-authoring-pack
> code --install-extension docsmsft.docs-images
> code --install-extension docsmsft.docs-markdown
> code --install-extension docsmsft.docs-metadata
> code --install-extension docsmsft.docs-preview
> code --install-extension docsmsft.docs-yaml
> code --install-extension donjayamanne.jquerysnippets
> code --install-extension DotJoshJohnson.xml
> code --install-extension dracula-theme.theme-dracula
> code --install-extension eppz.eppz-code
> code --install-extension esbenp.prettier-vscode
> code --install-extension formulahendry.code-runner
> code --install-extension gerane.Theme-FlatlandMonokai
> code --install-extension jakebathman.mysql-syntax
> code --install-extension jebbs.plantuml
> code --install-extension joshpeng.theme-onedark-sublime
> code --install-extension jprestidge.theme-material-theme
> code --install-extension liviuschera.noctis
> code --install-extension mathiasfrohlich.Kotlin
> code --install-extension mgmcdermott.vscode-language-babel
> code --install-extension michelemelluso.code-beautifier
> code --install-extension monokai.theme-monokai-pro-vscode
> code --install-extension ms-python.anaconda-extension-pack
> code --install-extension ms-python.python
> code --install-extension ms-vscode.typescript-javascript-grammar
> code --install-extension oscarcs.dart-syntax-highlighting-only
> code --install-extension rbbit.typescript-hero
> code --install-extension redhat.vscode-yaml
> code --install-extension SanaAjani.taskrunnercode
> code --install-extension sldobri.bunker
> code --install-extension slevesque.vscode-autohotkey
> code --install-extension spences10.vba
> code --install-extension streetsidesoftware.code-spell-checker
> code --install-extension teabyii.ayu
> code --install-extension techer.open-in-browser
> code --install-extension zanza00.random-theme-switcher
> code --install-extension zhuangtongfa.material-theme

**Comment by Denis-net** [comment]
Thanks,

Windows had to update itself...🙄😅😂

I restored almost all the extensions.
When the popup appeared, i selected "both" and then i pressed "Esc":
![immagine](https://user-images.githubusercontent.com/45769702/71885756-4a716b80-313b-11ea-8d97-23cb7fbf1b5c.png)
This is what I saw immediately next.

Two suspicious things:

* from my end i don't see the key "randomThemeSwitcher.switchMode" but this is because i didn't alter the settings.
* from your end you have installed an extension manually i suppose: the first line you posted isn't a marketplace extension (i think so because VSC don't see it as a valid extension id)

After the second startup the extension didn't open the popup.

Pheraps could be the unpacked extension that cause the issue, not sure, but worked on the VM
(I also updated VSC and retried again)

**Comment by Denis-net** [comment]
![immagine](https://user-images.githubusercontent.com/45769702/71887010-84437180-313d-11ea-9734-8f20d4121585.png)
I tried your setting and it worked too (but as i thought "Ayu One"  isn't recognized)

![immagine](https://user-images.githubusercontent.com/45769702/71887114-b9e85a80-313d-11ea-80d1-12c63b67174e.png)
And this is after relaunching VSC

The only thing left is the manually installed extension.
![immagine](https://user-images.githubusercontent.com/45769702/71887345-2c593a80-313e-11ea-935b-b6125108024b.png)
![immagine](https://user-images.githubusercontent.com/45769702/71887365-3713cf80-313e-11ea-83eb-32fed2bee722.png)

The one that don't appear here.

Try to temporarily remove it and try again.

**Comment by Denis-net** [comment]
I tried to install two .vsix extensions, but the extension still works 😭

The strange thing is that even in .vsix extensions i can read their id.
So What is this :  `code --install-extension trfr2h5mxe6eyejgts4uaakmutbhor5ric2zlvrh5yxuswlt326a.webassembly`
?

Could you send me your settings.json ?
(in order to have the nearest environment possible.)

**Comment by rediffusion** [comment]
> code --install-extension trfr2h5mxe6eyejgts4uaakmutbhor5ric2zlvrh5yxuswlt326a.webassembly

 Syntax Highlighting for .wasm files.

> Could you send me your settings.json ?

[settings.zip](https://github.com/zanza00/random-theme-switcher/files/4030684/settings.zip)

> If you hit Ctrl+K Ctrl+Shift+T("Switch to a Random Theme") nothing happens ?

 This combinations aren't binding.

Nothing's working anyway, bro.

**Comment by Denis-net** [comment]
I found it !!! 🎉🎊

There are two main errors plus one issue horrible:

1) you have an issue with missing colons:
``` JSON
"editor.fontSize": 16
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
```
After the fontSize value (16) there must be a *,*
i.e.:
``` JSON
"editor.fontSize": 16,
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
```
The same for:
```
"ahk.defaultArgs": "/r"
  "ahk.onArgs.run": true,
```
after "/r":
```
"ahk.defaultArgs": "/r",
  "ahk.onArgs.run": true,
```

Otherwise you will provide an unanalyzable file and VSC won't even be able to update it.

The other thing is more sneaky:
![immagine](https://user-images.githubusercontent.com/45769702/71900893-01cba980-315f-11ea-9d48-483101085763.png)

The "<?>" means that the letter even though are correctly (except space) displayed aren't valid.
So if you try to fix the colons you'll see that the workbench.colorTheme changes upon startup,
but the theme stays the same.
If you hover the cursor over the squiggles, you'll read "Theme is unknown or not installed".
This will also happen if you restart vscode or change theme with the binding:
![immagine](https://user-images.githubusercontent.com/45769702/71901135-8b7b7700-315f-11ea-864c-6a12cb15f566.png)
(btw, why can't you see the binding? how is it possible to disable extension suggested bindings ?)

To fix i suggest you to one or both the following things:

* empty the "randomThemeSwitcher.themeList" key,
* invoke the command "Copy installed theme"
* using the pencil changing the theme and copy the resulting string into the  list : "randomThemeSwitcher.themeList":[<PASTE-HERE>]

![immagine](https://user-images.githubusercontent.com/45769702/71904109-cc768a00-3165-11ea-8adf-51305e6ca683.png)

This should fix your issue.

**Comment by Denis-net** [comment]
Using [HEX](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump):
![immagine](https://user-images.githubusercontent.com/45769702/71909652-be7a3680-3170-11ea-872d-dafcb256c83c.png)
You can see that spaces are causing issues.
(I have used the pencil and compared the two versions of "Noctis Minimus" and I used a Sticky for better align the two strings);

I'm glad it worked !🎉🎊
Enjoy !😄

**Comment by rediffusion** [comment]
> There are two main errors plus one horrible issue:

 I've corrected all the comas!

> settings.json should not be with comments

It's simple for me to find what I need without it I'm like a blind cat.

> The other thing is more sneaky:

Yes, I do a mistake when I copied entires to .json file directly as you said before. ✌️

---

## How was the problem solved?

1.  Corrected all the comas!

2.  All I left was this key `"workbench.colorTheme": "eppz!",` and yours was removed.

3.  Restarted the IDE.

Then I saw these entries at the very end of the keys (without any interference on my part):

```
  // Autohotkey Manager:     
  "ahk.defaultArgs": "/r",
  "ahk.onArgs.run": true,
  "ahk.onSave.run": true,
"ahk.displaySwitchButton": true,
"randomThemeSwitcher.themeList": [
    "Ayu One",
    "Dracula Soft",
    "eppz!",
    "Flatland Monokai",
    "Sublime Material Theme - Dark",
    "Noctis Minimus",
    "Dobri Next -A07- Oxford",
    "One Dark Pro"
]
}
```
 

> btw, why can't you see the binding?

With bindings problem also was fixed, YAY! 🎈🔫

**Comment by rediffusion** [comment]
@Denis-net 

 🙈 It's me again. The question is, how do you set the theme daily? Used these keys with no result:

```
"randomThemeSwitcher.switchMode": "daily",
"randomThemeSwitcher.lastSwitchDay": 1
```

 After restarting the IDE theme changes like he's shuffling cards. Tested and works only these:

> manual
> typings

_What's wrong with me again?_  😕

**Comment by Denis-net** [comment]
With you ? Nothing
With the extension ? I forgot a parameter, so the `lastSwitchDay` is readed but not written😅.
I opened a PR in order to fix it. 👍🏼

**Comment by rediffusion** [comment]
10x, you're very attentive. [Merry Christmas](https://youtu.be/HQL76PuTWbk) bro.

![Merry Christmas](https://user-images.githubusercontent.com/30071027/72039284-80d2f600-32b5-11ea-82d6-454470caee6e.png)

**Comment by Denis-net** [comment]
P.S. I found [this extension](https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins) that can be very useful in spotting this kind of issues.

Cheers !

**Comment by ghost** [comment]
I'm closing this because it's now part of the extension.
But stay tuned because new features are coming ! 😉👍🏼
(I have also added a linter that will spot invalid theme names for you)
